name: user_signup
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^3.1.2
  flutter_verification_code: ^1.1.7
  intl_phone_field: ^3.2.0
  lottie: ^2.7.0
  flutter_svg: ^0.22.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  firebase_auth: ^4.13.0  
  firebase_core: ^2.22.0
  font_awesome_flutter: ^10.6.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"

flutter:
  uses-material-design: true
  assets:
    - assets/images/signup.json
    - assets/images/login.json
    - assets/images/otp.png
    - assets/images/
    - assets/icons/

fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Regular.ttf
      - asset: assets/fonts/Montserrat-Bold.ttf

  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-Bold.ttf
